#!/usr/bin/env python3
"""Generate the committed, dependency-free GitHub Pages HTML."""
import argparse
import html
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BASE = "https://shellyyang00-oss.github.io/"
SCHOLAR = "https://scholar.google.com/citations?hl=en&amp;user=ShQ3XMwAAAAJ"
PAGES = [
    ("index.html", "about", "About", "Xiaoqiu (Shelly) Yang | Penn Bioengineering", "Xiaoqiu (Shelly) Yang is a Penn Bioengineering Ph.D. student studying how mechanical forces and serotonin signaling contribute to mitral valve disease."),
    ("research.html", "research", "Research", "Research | Xiaoqiu (Shelly) Yang", "Research on PIEZO1, serotonin signaling, and extracellular matrix remodeling in human mitral valve cells at the University of Pennsylvania."),
    ("publications.html", "publications", "Publications", "Publications | Xiaoqiu (Shelly) Yang", "Selected publications by Xiaoqiu Yang on mitral valve mechanobiology, vascular redox signaling, and cardiovascular nanomaterials."),
    ("experience.html", "experience", "Experience", "Experience | Xiaoqiu (Shelly) Yang", "Research experience, education, awards, and mentoring at the University of Pennsylvania, Yale University, and Boston University."),
    ("contact.html", "contact", "Contact", "Contact | Xiaoqiu (Shelly) Yang", "Contact Xiaoqiu (Shelly) Yang, a Ph.D. student in Bioengineering at the University of Pennsylvania, for research inquiries and collaborations."),
    ("404.html", "404", "", "Page not found | Xiaoqiu (Shelly) Yang", "Find Xiaoqiu Yang's research, publications, and academic experience."),
]
PERSON = {
    "@context": "https://schema.org", "@type": "Person",
    "name": "Xiaoqiu Yang", "alternateName": "Shelly Yang", "url": BASE,
    "image": BASE + "assets/img/profile.jpg", "email": "mailto:xiaoqiuy@seas.upenn.edu",
    "sameAs": ["https://scholar.google.com/citations?hl=en&user=ShQ3XMwAAAAJ"],
    "affiliation": {"@type": "CollegeOrUniversity", "name": "University of Pennsylvania"},
    "alumniOf": [{"@type": "CollegeOrUniversity", "name": "Boston University"}],
    "jobTitle": "Ph.D. Student in Bioengineering",
    "knowsAbout": ["Mitral valve mechanobiology", "PIEZO1 mechanotransduction", "Serotonin signaling", "Extracellular matrix remodeling", "Cardiovascular redox biology"],
}


def render(page):
    filename, source, label, title, description = page
    prefix = "/" if filename == "404.html" else ""
    canonical = BASE if filename == "index.html" else BASE + filename
    navigation = "\n".join(
        f'        <a href="{prefix}{target}"' + (' aria-current="page"' if target == filename else '') + f'>{name}</a>'
        for target, _, name, _, _ in PAGES if name
    )
    structured = f'<script type="application/ld+json">{json.dumps(PERSON, ensure_ascii=False)}</script>' if filename == "index.html" else ""
    robots = '<meta name="robots" content="noindex">' if filename == "404.html" else ""
    body = (ROOT / "content" / f"{source}.html").read_text()
    return f'''<!doctype html>
<!-- Generated by scripts/build.py from content/{source}.html. -->
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{html.escape(title)}</title>
  <meta name="description" content="{html.escape(description)}">
  <meta name="author" content="Xiaoqiu (Shelly) Yang">
  <meta name="theme-color" content="#f8f7f3">
  <link rel="canonical" href="{canonical}">
{robots}
  <meta property="og:title" content="{html.escape(title)}">
  <meta property="og:description" content="{html.escape(description)}">
  <meta property="og:type" content="{'profile' if filename == 'index.html' else 'website'}">
  <meta property="og:url" content="{canonical}">
  <meta property="og:image" content="{BASE}assets/img/og.png">
  <meta property="og:image:width" content="1200">
  <meta property="og:image:height" content="630">
  <meta property="og:image:alt" content="Xiaoqiu (Shelly) Yang, Penn Bioengineering: cardiovascular mechanobiology">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="{html.escape(title)}">
  <meta name="twitter:description" content="{html.escape(description)}">
  <meta name="twitter:image" content="{BASE}assets/img/og.png">
  <link rel="icon" href="{prefix}assets/img/favicon.svg" type="image/svg+xml">
  <link rel="stylesheet" href="{prefix}styles.css">
  <script src="{prefix}assets/site.js" defer></script>
{structured}
</head>
<body>
  <a class="skip-link" href="#main">Skip to content</a>
  <header class="site-header">
    <div class="container masthead">
      <a class="brand" href="{prefix}index.html" aria-label="Xiaoqiu Yang, About"><span class="brand-mark" aria-hidden="true">XY</span><span class="brand-name">Xiaoqiu Yang</span></a>
      <div class="masthead-links">
        <a class="desktop-link" href="mailto:xiaoqiuy@seas.upenn.edu">Email <span aria-hidden="true">↗</span></a>
        <a class="desktop-link" href="{SCHOLAR}">Google Scholar <span aria-hidden="true">↗</span></a>
        <a class="cv-link" href="{prefix}assets/cv/Xiaoqiu_Yang_Resume.pdf">CV <span aria-hidden="true">↗</span></a>
      </div>
    </div>
    <div class="nav-wrap"><nav class="container page-nav" aria-label="Main navigation">
{navigation}
    </nav></div>
  </header>
  <main id="main" tabindex="-1">
{body}
  </main>
  <footer class="site-footer"><div class="container footer-inner"><p>© <span data-year>2026</span> Xiaoqiu (Shelly) Yang</p><div class="footer-links"><a href="{prefix}contact.html">Contact</a><a href="{SCHOLAR}">Google Scholar <span aria-hidden="true">↗</span></a><a href="{prefix}assets/cv/Xiaoqiu_Yang_Resume.pdf">Curriculum vitae <span aria-hidden="true">↗</span></a></div></div></footer>
</body>
</html>
'''


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Check that committed pages match their sources")
    args = parser.parse_args()
    outputs = {page[0]: render(page) for page in PAGES}
    locations = [BASE if page[0] == "index.html" else BASE + page[0] for page in PAGES if page[2]]
    outputs["sitemap.xml"] = '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' + "".join(f"  <url><loc>{url}</loc></url>\n" for url in locations) + "</urlset>\n"
    stale = []
    for filename, content in outputs.items():
        target = ROOT / filename
        if args.check:
            if not target.exists() or target.read_text() != content:
                stale.append(filename)
        else:
            target.write_text(content)
    if stale:
        raise SystemExit("Generated files are out of date: " + ", ".join(stale))
    print(f"{'Checked' if args.check else 'Generated'} {len(outputs)} static files.")


if __name__ == "__main__":
    main()
